[package]
name = "quizduell"
version = "0.1.0"

[dependencies]
diesel = { version = "1.3.2", features = ["postgres"] }
dotenv = "0.13.0"
hyper = "0.12"
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"
futures = "0.1.23"
